#!/bin/sh

[ "$2" = clipboard ] || exit 0

case $1 in
  -i)
    # Prevent copying if no input is provided (fix for Micro startup issue)
    data=$(cat && echo .); data=${data%.}
    if [ -z "$data" ]; then
      exit 0
    fi

    # Encode in Base64 and send via OSC 52
    printf "\033]52;;%s\a" "$(printf %s "$data" | base64 -w0)" > /dev/tty
    ;;
  -o)
    # Pasting is not supported via OSC 52
    exit 1
    ;;
esac
